---
title: "Traffic Fines Data Shiny"
author: "Jacob"
date: '2022-07-28'
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("lubridate")
library("ggplot2")
library("shiny")
library("here")
```

## Test script for data summaries

```{r traffic_data_load, echo=FALSE}
traffic_fines <- read.csv(file.path(here("data"),"/Traffic_camera_offences_and_fines.csv"))

# Prepare Dataset
traffic_fines <- traffic_fines %>%
  mutate(Offence_Month=parse_date_time(Offence_Month,"bY")) %>% # change Month to date format
  mutate(Rego_State=as.factor(Rego_State))

# Create Counts Data
monthly_fines <- traffic_fines %>%
  group_by(Offence_Month, Rego_State) %>%
  summarise(offence_count=n())

# Get list of States in the Data
getstates <- as.vector(levels(traffic_fines$Rego_State),mode="list")
names(getstates) <- levels(traffic_fines$Rego_State)
names(getstates)[1] <- "Missing"
```

## Offences Per Month Plot

```{r facet_plots, echo=FALSE}
ggplot(data=monthly_fines %>% filter(Rego_State %in% c("ACT","QLD","NSW","WA","NT")), aes(x=Offence_Month, y=offence_count) ) +
  geom_line() +
  facet_grid(Rego_State ~ .) +
  ggtitle("Number of Offences By Time and Vehicle Registration State") + xlab("Time") + ylab("Offence Count")

```

## Interacive Shiny Plot
```{r plotdata, echo=FALSE}

# Add checkboxes for State
checkboxGroupInput("checkGroup", 
                            h3("Select Series to Plot"), 
                            choices = getstates,
                            selected = "ACT"
                   )
  
renderPlot({
  
  # Filter data based on ueser input
  monthly_fines_filtered <- monthly_fines %>% filter(Rego_State %in% input$checkGroup)
  
  # Plot New Series
  ggplot(data=monthly_fines_filtered, aes(x=Offence_Month, y=offence_count, col=Rego_State) ) +
    geom_line() +
    geom_smooth() +
    ggtitle("Number of Offences By Time and Vehicle Registration State") + 
    xlab("Time") + 
    ylab("Offence Count") 

})

```

